### ISSUE TITLE
Use model properties to populate dropdowns

### ISSUE THREAD

**Issue by tinyweasel** [adfinis-sygroup/ember-validated-form#10]
Can this be possible, instead of having to hard code the list of dropdown options? For example I have a book model, which has an author property, and each of these has an API endpoint so there would be a list of authors at the author endpoint. Is it possible to use these to populate an author dropdown in order to update the book model's author property?

**Comment by tinyweasel** [comment]
Found a way, thanks!

**Comment by czosel** [comment]
Great! Would you mind sharing some code how you solved this? It might be interesting to add this to the docs. Thanks!

**Comment by tinyweasel** [comment]
Sure, it's kind of a hacky way as I'm not mad familiar with ember, but it basically creates an array out of the properties and then you can use that array as your options.

```
modelOptions: Ember.computed(function() {
		return this.store.peekAll('model').map(function(o){return o.get('property');});
	})
```
