### ISSUE TITLE
Disabled flag does not seem to work on text input

### ISSUE THREAD

**Issue by tinyweasel** [adfinis-sygroup/ember-validated-form#11]
I need to apply "disabled=noEdit" flags to all my edit fields. Works on selects but not text or textarea.

**Comment by czosel** [comment]
Thanks for the suggestion! For me, `disabled` didn't even work for selects.
I created a PR that should fix this and we'll release a new version once it has been reviewed and merged!

**Comment by tinyweasel** [comment]
Superb! Thanks!

**Comment by czosel** [comment]
We just released version 0.1.8 with support for `disabled`. Feel free to reopen the issue if something is not working for you!
