### ISSUE TITLE
Disabling input (text) causes the value to be missing

### ISSUE THREAD

**Issue by omairvaiyani** [adfinis-sygroup/ember-validated-form#120]
I want to display the text value in an input field, but disable edit. I assumed that setting ```disabled=true``` would result in this, but it causes the value to be empty - it does however disable the input element as expected.

Anyone got this issue?

**Comment by czosel** [comment]
Hi @omairvaiyani, i wasn't able to reproduce the issue:
https://ember-twiddle.com/3691a8576c35ff149bfc26a564ec5437?openFiles=templates.application.hbs%2C
Can you try tweaking the twiddle and post your reproduction here?
