### ISSUE TITLE
Autosuggest in dropdowns

### ISSUE THREAD

**Issue by tinyweasel** [adfinis-sygroup/ember-validated-form#13]
Is it possible to have a regex type search in the top part of a select input to quickly select one of the options in a dropdown? We have a dropdown with maybe 200 entries. Thanks for the addon!

**Comment by czosel** [comment]
Unfortunately, there's no native HTML input element that provides this kind of functionality. If grouping the elements in your dropdown is not enough, you'll probably have to look out for a custom component (maybe something like [this](http://semantic-org.github.io/Semantic-UI-Ember/#/modules/search)) - in any case, this is out of scope for this addon.
Good luck!

**Comment by tinyweasel** [comment]
Cool, thanks for the recommendation!
