### ISSUE TITLE
TODO: Migrate from ember-i18n to ember-intl

### ISSUE THREAD

**Issue by jacobq** [adfinis-sygroup/ember-validated-form#137]
This addon appears to [still use](https://github.com/adfinis-sygroup/ember-validated-form/blob/b78f6daaf9d1ba441a322c6f4734bdba187f4e03/package.json#L64) [`ember-i18n`](https://github.com/jamesarosen/ember-i18n), which has been deprecated in favor of [`ember-intl`](https://github.com/ember-intl/ember-intl). Please consider migrating.

**Comment by chrisvdp** [comment]
Any way we could get a release with this fix?
