### ISSUE TITLE
Select multiple and selectedValue in dropdowns

### ISSUE THREAD

**Issue by tinyweasel** [adfinis-sygroup/ember-validated-form#14]
I'm making a dropdown which is populated with data from a model, that can be updated with this edit form. The model might have two properties, eg, the book model might have two authors, so when the book model is being edited, the author dropdown should be populated with the list of all possible authors, with the two existed authors preselected, and you should have the ability to select more. Could this be possible?

**Comment by czosel** [comment]
I just released v0.1.9, which adds support for `multiple`. Prefilling the select with a given value should work out of the box, if your model is correctly initialized! For details please also check [the docs of ember-one-way-controls](https://github.com/DockYard/ember-one-way-controls/blob/master/docs/one-way-select.md#multiple-select).

**Comment by czosel** [comment]
I'll close this since this should be working now. Feel free to reopen the issue if I'm mistaken or if you have further questions related to this!

**Comment by tinyweasel** [comment]
Yep, is working, thanks!
