### ISSUE TITLE
Bootstrap classes not generating 

### ISSUE THREAD

**Issue by patelbhavika46** [adfinis-sygroup/ember-validated-form#140]
I have installed ember-validated-form package and try to create form. validations and all working properly but bootstrap classes are not generating. I don't know why. I set configuration in environment.js and my form looks like same as given example in this https://adfinis-sygroup.github.io/ember-validated-form/.

**Comment by czosel** [comment]
Hi @patelbhavika46,

Can you share some more information? Most importantly, which version of the addon are you using? Can you post the configuration you did in `environment.js` and the HTML output you're seeing?

**Comment by patelbhavika46** [comment]
> Hi @patelbhavika46,
> 
> Can you share some more information? Most importantly, which version of the addon are you using? Can you post the configuration you did in `environment.js` and the HTML output you're seeing?

environment.js

` module.exports = function (environment) { 

    var ENV = {

            modulePrefix: 'client',

            environment: environment,

            baseURL: '/xyz',

            rootURL: '/xyz',

            locationType: 'router-scroll',

            historySupportMiddleware: true,

            defaultDateFormat: 'L', // for moment.js

            defaultDatePickerFormat: 'm/d/Y', // for flatpickr

            defaultNumberFormat: '0,0', // for numeral.js

            EmberENV: {
                FEATURES: {
                    // Here you can enable experimental features on an ember canary build
                    // e.g. 'with-controller': true
                }
            },

            APP: {
                // Here you can pass flags/options to your application instance
                // when it is created
            },

            'ember-validated-form': {
                label: {
                  submit: "Go for it!"
                },
                css: {
                  // bootstrap classes
                  group: "form-group",
                  control: "form-control",
                  label: "form-label",
                  checkbox: "checkbox",
                  radio: "radio",
                  help: "help-block",
                  hint: "help-block",
                  button: "btn btn-default",
                  submit: "btn btn-primary"
                }
            }
        };

    ENV.i18nextOptions = {
        joinArray: "\n",
        joinArrays: "\n",
        ns: [
            'utils',
            'format',
            'translation'
        ],
        backend: {
            loadPath: ENV.rootURL + '/locales/{{lng}}/{{ns}}.json',
        },
    };

    if (environment === 'development') {
        ENV.APP.LOG_ACTIVE_GENERATION = true;
        ENV.APP.LOG_TRANSITIONS = true;
        ENV.isProductionLike = false;
    }

    if (environment === 'test') {
        // Testem prefers this...
        ENV.baseURL = '/';
        ENV.rootURL = '/';
        ENV.locationType = 'none';

        // keep test console output quieter
        ENV.APP.LOG_ACTIVE_GENERATION = false;
        ENV.APP.LOG_VIEW_LOOKUPS = false;

        ENV.APP.rootElement = '#ember-testing';
        ENV.isProductionLike = false;
    }

    if (environment === 'production') {
        ENV.isProductionLike = true;
    }

    ENV['ember-cli-bem'] = {
        elemDelimiter: '__',
        modDelimiter: '--',
        useKeyValuedMods: true,
    };

    return ENV;

};`

Form template:
`{{#modal/modal-dialog
    id="modal-award-kudows"
    title=(t 'badge.titles.issueKudos')
    close="closeModal"
    showHeader=true
    modal-title-id="modal-title-award-kudows"
    onShown="onShown"
    onHidden="onHidden"
    medium=true
}}

    {{#validated-form
      model = (changeset model)
      on-submit = (perform submit)
      class="form-horizontal form-label-top"
      as |f|}}

        {{#modal/modal-dialog-body}}

            <div class="award-kudos-modal__content">
                <div class="award-kudos-modal__text">
                    {{t 'badge.messages.textContent'}}
                </div>
                <div class="award-kudos-modal__remaining-xp-info custom-tooltip">
                    <span class="award-kudos-modal__xp-number"> {{communityState.remainingPointsToAward}} </span>
                    <span class="award-kudos-modal__xp-text"> Remaining XP </span>
                    <span class="tooltiptext">{{t 'badge.messages.tooltipText'}}</span>
                </div>
            </div>
            <br/>
            <div>
                {{f.input type="hidden" value=communityState.id name="userId" required= true}}
                    {{f.input
                        type             = 'select'
                        label            = 'Reason'
                        name             = 'reason'
                        includeBlank     = 'Select a Reason'
                        options          = awardmentReasons
                        onchange         = 'handleReasonChange'
                        optionValuePath  = "id"
                        optionLabelPath  = "title"
                        required         = true
                    }}
                    {{f.input
                        type     = 'textarea'
                        value    = message
                        label    = "Message"
                        name     = 'message'
                        rows     = '6'
                        cols     = '22'
                        required = true
                    }}
                <div>
                    {{f.input type="hidden" value=xp name="point" label=(t 'How many points would you like to award?') class="xp-number" required= true}}
                    <div class="award-points">

                        {{#each communityState.pointAmountJsonArray as |point|}}

                            <div class="award-points__xp" id={{concat "xp-" point}} {{action "setXpNumber" point}}>
                                <span class="award-points__xp-number">{{point}}</span><span class="award-points__xp-text">xp</span>
                            </div>

                        {{/each}}

                    </div>
                </div>
            </div>

        {{/modal/modal-dialog-body}}

        {{#modal/modal-dialog-footer}}

            {{#modal/modal-dialog-close}}

                {{t 'actions.cancel'}}

            {{/modal/modal-dialog-close}}

            <button type="submit" class="btn btn-primary" disabled={{submitting}}>
                {{t 'actions.confirm'}}
            </button>

        {{/modal/modal-dialog-footer}}
    {{/validated-form}}

{{/modal/modal-dialog}}
` 

Form UI:
<img width="325" alt="form" src="https://user-images.githubusercontent.com/20592563/51840149-502ec200-22d9-11e9-96f3-58b205a3e723.PNG">

Please let me know if you need more information. I need to resolve this as soon as possible. Please help me.

**Comment by czosel** [comment]
Just some obvious questions:

- Did you confirm that you're using version 1.4.2?
- Is bootstrap working properly outside of the form?
- Can you paste the generated HTML output of the form?

**Comment by quaintjames** [comment]
Hi - I'm having the same issue. 

- version 2.0.0-alpha.5
- bootstrap works outside the form

Here's the HTML I get:
`<form id="ember352" class="ember-view">
    <div id="ember360" class="ember-view">  <label for="df479d6d-dd4f-496e-9d57-5350196bdd12" id="ember361" class="ember-view">First name *
</label>
  <input name="firstName" id="df479d6d-dd4f-496e-9d57-5350196bdd12" class="ember-view" type="text">


</div>
      <button id="ember370" class="ember-view" type="submit">Save
</button>
</form>` 

I noticed that the environment config wasn't pulling in correctly - looks like there are 2 reasons for that

1. I had to set `import config from "../../config/environment";` as opposed to "../config/environment";` in validated-form/component.js (I use pods)
2. Having done that, `config: config["ember-validated-form"]` was grabbing all of my ENV - not just the ["ember-validated-form"] part - so now I've got the config in its own file: 

`// components/ember-validated-form/config.js

const embervalidatedform = {
  label: {
    submit: "Go for it!"
  },
  css: {
    // bootstrap classes
    form: "formstylelelksdjf",
    text: "form-group",
    group: "form-group",
    radio: "radio",
    control: "form-control",
    label: "col-form-label",
    help: "small form-text text-danger",
    hint: "small form-text text-muted",
    checkbox: "checkbox",
    button: "btn btn-default",
    submit: "btn btn-primary",
    loading: "loading",
    valid: "is-valid",
    error: "is-invalid",
    select: "custom-select custom-select-lg mb-3"
  }
}

export default embervalidatedform;`

and I'm importing it here:

`// components/ember-validated-form/component.js

import ValidatedForm from "ember-validated-form/components/validated-form";
import config from "./config";

export default ValidatedForm.extend({
  config: config,

  init(){
    this._super(arguments);
    console.log(config);
  }
});`

When it logs the config, I get: 
`{
  "label": {
    "submit": "Go for it!"
  },
  "css": {
    "form": "formstylelelksdjf",
    "text": "form-group",
    "group": "form-group",
    "radio": "radio",
    "control": "form-control",
    "label": "col-form-label",
    "help": "small form-text text-danger",
    "hint": "small form-text text-muted",
    "checkbox": "checkbox",{
  "label": {
    "submit": "Go for it!"
  },
  "css": {
    "form": "formstylelelksdjf",
    "text": "form-group",
    "group": "form-group",
    "radio": "radio",
    "control": "form-control",
    "label": "col-form-label",
    "help": "small form-text text-danger",
    "hint": "small form-text text-muted",
    "checkbox": "checkbox",
    "button": "btn btn-default",
    "submit": "btn btn-primary",
    "loading": "loading",
    "valid": "is-valid",
    "error": "is-invalid",
    "select": "custom-select custom-select-lg mb-3"
  }
}
    "button": "btn btn-default",
    "submit": "btn btn-primary",
    "loading": "loading",
    "valid": "is-valid",
    "error": "is-invalid",
    "select": "custom-select custom-select-lg mb-3"
  }
}`

So that looks like it all *should* be working. I just don't understand where exactly the classes get applied to the fields, so I'm stumped.

**Comment by quaintjames** [comment]
Ah! Found the answer - because I'm using 2.0.0-alpha.5 I need to use 

```
"ember-validated-form": {
    theme: "bootstrap"
  }
```

see: https://github.com/adfinis-sygroup/ember-validated-form/issues/136
