### ISSUE TITLE
queue is not a helper

### ISSUE THREAD

**Issue by quaintjames** [adfinis-sygroup/ember-validated-form#146]
in v2, the radio-group and the checkbox templates both make calls to a 'queue' helper as follows:

`onclick  = {{action (queue (action update option.key) setDirty)}}`

Unfortunately I can't find what the 'queue' helper refers to. I've worked around it temporarily by removing the queue call from that template. Not sure if that's the best policy though.

**Comment by anehx** [comment]
Hi, the `queue` helper is from an addon called `ember-composable-helpers` (https://github.com/DockYard/ember-composable-helpers#queue). However, you do not have to use that helper if you don't want to. The actions can be called directly on the component..
