### ISSUE TITLE
support for custom component usage should be improved

### ISSUE THREAD

**Issue by feanor07** [adfinis-sygroup/ember-validated-form#16]
Custom component usage seems to be needing some improvement; because the addon already provides label and error showing for built-in types such as select, text-input, etc. However; when a developer wants to use a custom component he is not able to give the same look&feel (css settings, etc.) like the built-in components. A proper yielding of necessary attributes from `validated-input.hbs` should enable better custom component leveraging and enable usage of `validated-input` in block form; which gives quite a lot of power to the developers.

**Comment by czosel** [comment]
This sounds like a really good idea. If you find the time to provide a PR that makes this possible, I'd be happy to merge it!

**Comment by feanor07** [comment]
I have already done that;  take a look at my pull request if you have time. thx.

**Comment by czosel** [comment]
Merged it - thanks again!

**Comment by feanor07** [comment]
this was a really fast merge; it was fun to contribute.

**Comment by czosel** [comment]
:smile: It was also fun to merge this, don't hesitate to open an issue/PR next time you have a suggestion!
