### ISSUE TITLE
Hide save button based on boolean

### ISSUE THREAD

**Issue by tinyweasel** [adfinis-sygroup/ember-validated-form#19]
This would be straightforward to do with a real button like {{if notEditing 'hidden'}}, but is there a way to do it with this automatically generated button?

**Comment by czosel** [comment]
Hi @tinyweasel, thanks for the suggestion! With #20 we'll start yielding the submit button instead of automagically rendering it, which should offer much more flexibility. I'll let you know when it has been merged and released!

**Comment by czosel** [comment]
Version 0.2.0 was just released! Please see the [changelog](https://github.com/adfinis-sygroup/ember-validated-form/blob/master/CHANGELOG.md) for a little upgrade guide.

**Comment by tinyweasel** [comment]
Super! Thanks!
