### ISSUE TITLE
Ember 2.13 Fails with helper validated-form not found.

### ISSUE THREAD

**Issue by steverhoades** [adfinis-sygroup/ember-validated-form#30]
```
$ ember install ember-validated-form
NPM: Installed ember-validated-form
Installed addon package.
```

controller.js
```
import Ember from 'ember';
import {
  validatePresence
} from 'ember-changeset-validations/validators';

export default Ember.Controller.extend({
  validators: {
    name: [validatePresence(true)]
  },

  actions: {
    submit() {

    }
  }
});

```

template.hbs
```
{{#validated-form
  model       = (changeset model validators)
  on-submit   = (action "submit")
  submit-label = 'Save' as |f|}}

  {{f.input label="Name" name="name"}}

  {{/validated-form}}
```

Results in:
```
Assertion Failed: A component or helper named "validated-form" could not be found
```

**Comment by steverhoades** [comment]
After researching this further, I don't believe this has anything to do with this add-on.

The issue appears to be with pods support.  I setup a new application without pods support and the add-on works just fine with 2.13.

This issue: https://github.com/emberjs/ember.js/issues/14699 has been closed, but I do believe there is some kind of problem still causing some add-ons to throw this error.

**Comment by steverhoades** [comment]
Since emberjs/ember.js#14699 is closed, I added a new issue here: https://github.com/emberjs/ember.js/issues/15331

**Comment by czosel** [comment]
Hi @steverhoades, thanks for following up on this! We're also using pods in our projects, but didn't try 2.13 yet. I subscribed to the issue you mentioned, curious what'll turn out!

**Comment by okachynskyy** [comment]
I have the same issue with Ember 2.12
I have added  "usePods": true to .ember-cli and podModulePrefix to environment.js, and then:
"A component or helper named "validated-form" could not be found"

**Comment by okachynskyy** [comment]
I have tried to move addon from pods structure to default structure, and after that everything is okay
https://github.com/adfinis-sygroup/ember-validated-form/pull/31

**Comment by czosel** [comment]
Hi @okachynskyy, thank you for following up on this! :+1: 

Since pods seem to be phased out, I'm more than happy to adapt to the default structure.
