### ISSUE TITLE
Accessing form data in action

### ISSUE THREAD

**Issue by dale42** [adfinis-sygroup/ember-validated-form#38]
I am converting a component to use ember-validated-form. The validation is working, it flags if no content is present, and it allows calling the "submit" action if content is present. 

When I try to access the entered form value (with `this.get('name')` ) I get undefined.

Is there a different convention for accessing form data?

Here is my component.js file:
- "addShow" is the old action
- "submit" is the new, ember-validated-form action.
```
import Ember from 'ember';
import UserValidations from '../validations/add-show-input';

export default Ember.Component.extend({

  UserValidations: UserValidations,

  actions: {
    addShow() {
      const model = this.get('model');
      const router = this.get('router');  // Provided by initializer
      const component = this;

      let newShow = model.store.createRecord('show', {
        name: this.get('name'),
      });
      return newShow.save().then(function () {
        component.set('name', '');  // Zero out field
        router.transitionTo('show', newShow);
      });
    },

    submit() {
      let showName = this.get('name');
      alert(showName);
    },

  }
});
```
Full code is available at https://github.com/dale42/showtime/tree/ember-validated-form-impl

Component:
- https://github.com/dale42/showtime/blob/ember-validated-form-impl/app/components/add-show-input.js
- https://github.com/dale42/showtime/blob/ember-validated-form-impl/app/templates/components/add-show-input.hbs

Component is used in this template:
- https://github.com/dale42/showtime/blob/ember-validated-form-impl/app/templates/show/index.hbs
on this route:
- https://github.com/dale42/showtime/blob/ember-validated-form-impl/app/routes/show/index.js

**Comment by czosel** [comment]
Hi @dale42, thanks for your (very well-written) bug report! :+1: 

The changeset (representing your model) is passed to the submit action explicitly as an argument:
```javascript
actions: {
  submit(model) {
    let showName = model.get('name');
    model.save();
  }
}
```

Currently, this is only documented if you're implementing the handler with ember-concurrency tasks:
```javascript
submit: task(function * (model) {
  yield model.save();
  // ... more code to show success messages etc.
})
```
I'll try to make this a little clearer in the README. 

I hope that'll solve your issue, otherwise let me know! :smile:

**Comment by czosel** [comment]
PS: I added a very simple submit handler to the example: https://github.com/adfinis-sygroup/ember-validated-form/commit/4b8c1741fdd82b8601bba9efdf1d135c3194aa58

**Comment by dale42** [comment]
Thanks so much for the answer! And the fast reply.
