### ISSUE TITLE
Unable to submit the form

### ISSUE THREAD

**Issue by g8anusha** [adfinis-sygroup/ember-validated-form#47]
Hi,

When I try to submit the form, I get the following error : 

```
ember.debug.js:16905 TypeError: method.apply is not a function
    at Backburner.join (ember.debug.js:773)
    at Function.run.join (ember.debug.js:21556)
    at ember.debug.js:9478
    at Object.flaggedInstrument (ember.debug.js:17747)
    at ember.debug.js:9477
    at runTaskOrAction (component.js:5)
    at component.js:60
    at tryCatch (ember.debug.js:58165)
    at invokeCallback (ember.debug.js:58177)
    at publish (ember.debug.js:58148)
```

Also, I see that the model that is being set inside the form, is not present outside anywhere. That is, if I try to get using this.get('model') which was the same that was given in {{validated-form}}, it is empty!!!

Please guide me! Thanks in advance!!

**Comment by czosel** [comment]
Hi @g8anusha,

could you please share some code (template and controller/component) that illustrates how you're submitting the form? - I haven't seen this issue before.

Thanks!

**Comment by g8anusha** [comment]
1. I am not able to use ember-concurrency, by giving a task in the controller. It throws exception, and also the save button doesn't get disabled.
2. Also, a new model is getting created in the validated-form, which doesn't affect the actual model created in the model hook of the route.

**app/routes/home.js**

```
model() {
	
	return Ember.RSVP.hash({
		homeModel: this.store.createRecord('homeModel', {});
	});
}
```

**app/controllers/home.js**

```
export default Ember.Controller.extend({
	HomeModelValidations,
	actions: {
		submit: task(function * (model) {
			yield model.save();
		}),
		cancel(model) {
			model.rollback(); // throws exception saying model.rollbackAttributes() is not a function
			this.transitionToRoute('index');
		},
		mutatingGender(model, value) {
			model.set('gender', this.store.peekRecord('gender', value));
			console.log(this.get('model.homeModel.gender')); // displays undefined
		}
	}
});
```

**app/templates/home.hbs**

```
<div class='ml-grid'>
	{{#validated-form model=(changeset model.homeModel HomeModelValidations) on-submit=(action 'submit') as |f|}}
	<div>
		{{f.input value='name' value='name'}}
		
		{{#f.input value='occupation' name='occupation' as |fi|}}
			{{#power-select
				options=occupation
				searchField='occupationName'
				onchange=fi.update
				required=true
				selected=f.model.occupation as |o|}}
			  {{o.occupationName}}
		    {{/power-select}}
		{{/f.input}}
		
		{{#f.input value='gender' name='gender' on-update=(action 'mutatingGender' f.model) as |fi|}}
			{{#each gender as |g|}}
			<div class='radio'>
				{{#one-way-radio 
					name = 'gender'
					value=g.id
					onchange=fi.setDirty
					update=fi.update
					required=true
					option=g.id}}
				{{/one-way-radio}}
				{{g.genderName}}
			</div>
			{{/each}}
		{{/f.input}}
		
		{{f.submit label='Save'}}
		
		<button {{action 'cancel' f.model}}> Cancel </button>
	</div>
	{{/validated-form}}
</div>
```

Please ignore the css parts for now. 

Thanks in advance!

**Comment by czosel** [comment]
Hi @g8anusha, a quick hint concerning your first point: The ember-concurrency task is not an action, it should be a property:
```javascript
export default Ember.Controller.extend({
	HomeModelValidations,
	submit: task(function * (model) {
		yield model.save();
	}),
        // ...
```
I'll get back to you concerning your second poin later! :smile:

**Comment by g8anusha** [comment]
Thanks @czosel, how do I use it in the template then??

**Comment by czosel** [comment]
Simply 
```Handlebars
{{#validated-form on-submit=submit  (...) }}
```
(This should probably be documented in our README... )

**Comment by g8anusha** [comment]
I tried the above way, but still throws error.

**Comment by czosel** [comment]
Hi @g8anusha,

You don't have to specify `disabled=true` manually. Since I couldn't reproduce your issue I created [a twiddle](https://ember-twiddle.com/3547207b06ed896f123332dd772503d0) that shows a minimal working demo using ember-concurrency tasks. 

I hope that'll help - if not, could you tweak the twiddle to reproduce the problem you're facing?

**Comment by g8anusha** [comment]
Thanks, I'll have a look at time.

meanwhile, can you give me a solution to the 2nd point I mentioned in the previous comments?

**Comment by czosel** [comment]
Hi @g8anusha,

Sorry, I totally forgot :sweat_smile: 

I wasn't able to reproduce your issue with `rollback`. Please see [this twiddle](https://ember-twiddle.com/3547207b06ed896f123332dd772503d0?openFiles=templates.application.hbs%2C) for a working demo.

As for the `mutatingGender` part - the way you implemented this seems quite complex - why not just use a `radioGroup` ([see docs](https://github.com/adfinis-sygroup/ember-validated-form#radio-button-group)) for this?

**Comment by g8anusha** [comment]
Hi @czosel , rollback is solved now.

But, the save button doesn't get disabled. In the twiddle it shows to be disabled, but in the local dev env it isn't showing as disabled.

**Comment by czosel** [comment]
Hi @g8anusha,

I'm happy to hear `rollback` is working for you now!

Concerning the disabled submit button, we'll need a reproduction to go forward. I'd suggest you try to simplify your local dev environment until it matches the twiddle. Another possibility is to set up a new ember app locally with a minimal example (like in the twiddle) and expand it to the more complex case you have currently. Either way, like this you should be able to find out what's introducing your issue.

You can also try to adapt the fiddle to match the dependency versions you have locally.

Good luck!

**Comment by g8anusha** [comment]
Hi @czosel,

I had misunderstood the usage of concurrency here using task. I was thinking that save will be disabled until all the fields are filled and valid. But, just now realised that it will be disabled until the save operation is finished. Sorry for that!

But, my question is right in a way. How do I disable the save button until all the fields are filled out?? Is there any way in ember-concurrency to achieve that?

**Comment by czosel** [comment]
Hi @g8anusha,

Ah, that explains the confusion :smile: 

Disabling the submit button is not officially supported because we believe it is not great for UX - it might leave people wondering why they can't submit the form. This is especially bad when not all form fields are dirty yet, because then they wouldn't even see any error messages. 

I just played around with this a little and it turns out to be possible, though: see [this fiddle](https://ember-twiddle.com/7693dda4ebdebcda2065c0b3087011c5?openFiles=templates.application.hbs%2C)

Let me know what you think! :wink:

**Comment by g8anusha** [comment]
Hurray! It's working! Thank you :) Will get in touch again if I face any more difficulties. :100: :1st_place_medal:

**Comment by czosel** [comment]
Awesome! :+1:
