### ISSUE TITLE
Latest version of the dependencies not added here yet

### ISSUE THREAD

**Issue by g8anusha** [adfinis-sygroup/ember-validated-form#69]
Hi @czosel,

Currently in ember-validated-form we do not have the facility to use nested models, as ember-changeset didn't have. But few days back, ember-changeset has updated their package with this one merged to their code. Can you please update your ember-changeset version so that I will be able to utilize this in my application? Also, please update README with the how-tos as well. Thank you :)

**Comment by czosel** [comment]
Hi @g8anusha,
wow, that's awesome! I definitely agree that we should update to the new version.
I probably won't find time in the next couple of days to do this - if you do, i'd be happy to look at your PR 😉

**Comment by nmccready** [comment]
see #74

**Comment by czosel** [comment]
Hi @g8anusha, we just updated to the latest versions of ember-changeset, and ember-changeset-validations. I didn't manage to get nested validations to work yet though, as this still seems to be an open issue in ember-changeset-validations. Let's leave your issue open until this is fixed and we have documentation for nested keys support.

**Comment by nmccready** [comment]
@czosel heads up https://github.com/poteto/ember-changeset/issues/256

**Comment by czosel** [comment]
@nmccready thanks for letting me know - i'll make a release containing #76 tomorrow.

**Comment by nmccready** [comment]
@czosel they seem to be getting close to finishing up the nested change-set support https://github.com/poteto/ember-changeset/pull/268

Released v1.4.2-beta.0
