### ISSUE TITLE
Fastboot issue?

### ISSUE THREAD

**Issue by onewiseburdman** [adfinis-sygroup/ember-validated-form#73]
There was an error running your app in fastboot. More info about the error: 
 Error: Assertion Failed: Underlying object for changeset is missing.

I followed the directions pretty closely.  I believe that I have everything configured correctly and I am getting this error-which does not appear prior to installing the add-on.

Did I somehow miss a step for Fastboot?  

Please help as this is holding me up right now.

**Comment by onewiseburdman** [comment]
Error:  
There was an error running your app in fastboot. More info about the error: 
 Error: Assertion Failed: Underlying object for changeset is missing
    at new EmberError (/Users/dad/Documents/workspace/io/tmp/broccoli_merge_trees-output_path-kR6gfOR9.tmp/assets/ember-debug/error.js:40:1)
    at assert (/Users/dad/Documents/workspace/io/tmp/broccoli_merge_trees-output_path-kR6gfOR9.tmp/assets/ember-debug/index.js:139:1)
    at changeset (/Users/dad/Documents/workspace/io/tmp/broccoli_merge_trees-output_path-kR6gfOR9.tmp/assets/addon-tree-output/ember-changeset/index.js:54:1)
    at new Changeset (/Users/dad/Documents/workspace/io/tmp/broccoli_merge_trees-output_path-kR6gfOR9.tmp/assets/addon-tree-output/ember-changeset/index.js:580:1)
    at changeset (/Users/dad/Documents/workspace/io/tmp/broccoli_merge_trees-output_path-kR6gfOR9.tmp/assets/addon-tree-output/ember-changeset-validations/helpers/changeset.js:20:1)

**Comment by onewiseburdman** [comment]
In furtherance-I installed a brand new ember application with only fast boot and your add-on the same result.

**Comment by czosel** [comment]
Hi @onewiseburdman, thanks for the bug report! I tried to reproduce the issue:

* ember 2.14: I also got an error, but a different one than you
* ember 2.17: Seems to work

Which version of ember are you using?

**Comment by onewiseburdman** [comment]
2.16.2

**Comment by onewiseburdman** [comment]
Will try and update now to see if it fixes the issue.

**Comment by onewiseburdman** [comment]
Great find - that indeed looks like it was the problem, I'm going to now test with bootstrap, assuming there are no more issues -I believe that solved it.  Might want to make a note of this somewhere...please don't close till I can verify that it all functions correctly.

**Comment by czosel** [comment]
I just tried with 2.16, and realized that your issue actually has a simple fix: The error said that the changeset is missing it's "underlying object", which is `model` in the case of the demo in our README. I realized that we forgot to add explicit instructions for this, so all you have to do is return something in your route's model hook, e.g.
```
  model() {
    return {
      firstName: 'Foo'
    }
  }
```
and the error will go away. 

It seems that Ember 2.17 handles the case where you don't have a route / a model hook differently, that's why it worked there out of the box.

I'll add something regarding the `model` to our README!

**Comment by czosel** [comment]
I updated the README. Let me know if the fix worked for you!

**Comment by onewiseburdman** [comment]
I think it's working-I am having a hard time connecting it to saving my form data to firebase.  I'm sorry if these are basic things, but I'm fairly new to Ember.JS-I just don't understand what the problem is and why it won't kick off the validations-instead it just returns in the browser url
> customer-settings? 
Nothing saves.  But without the validator it works.  

My Model:
`import DS from 'ember-data';

export default DS.Model.extend({
  blankpage: DS.attr('string'),
  timestamp: DS.attr('number')
});
`
My Validations File:
`import {
    validatePresence
  } from 'ember-changeset-validations/validators';

  export default {
    blankpage: [validatePresence(true)]
  };`

My Controller:
`import Controller from '@ember/controller';
import CustomersettingsValidations from '../validations/customersettings';

export default Controller.extend({
  
  CustomersettingsValidations,
    sortProperties: ['timestamp'],
    sortAscending: false, // sorts post by timestamp
    
    actions: {
      publishTheme: function() {
        var newTheme = this.store.createRecord('theme', {
          blankpage: this.get('blankpage'),
          timestamp: new Date().getTime()
        });
        newTheme.save();
      }
    }
});`

My HBS Template:
`<h2>New Post</h2>

 {{spectrum-color-picker color=blankpage}}

    
    {{#validated-form
  on-submit = publishTheme
  model     = (changeset model)
  value=blankpage
  as |f|}}
 
<ul >
  <li>
    {{f.input type=text value=blankpage placeholder="MainStageColor" required=true}}
  </li>
  <li>
     {{f.submit label="Save"}}
  </li>
</ul>
{{/validated-form}}

{{outlet}}`

My Router:

`import Route from '@ember/routing/route';
import EmberObject from '@ember/object';


export default Route.extend({
    model () {
        return EmberObject.create({});
      }
});`

**Comment by onewiseburdman** [comment]
Okay so I have the form semi-working, I can write data back and forth to firebase, but I seem to be struggling with getting it to actually validate.  Below is my form and my controller-everything is very basic.   I am not sure what the problem is,  the validations are literally to check if the field is required.  Please help!  I am pretty sure this is not related to the original issue, but nonetheless-I just need to get past this.

Thanks for all you do, and thanks for the awesome support. 

Form:

<h2>New Post</h2>
 {{spectrum-color-picker color=blankpage}}
    {{#validated-form
        model = (changeset model CustomersettingsValidations)
        submit = (action "publishTheme")
        as |f|
    }}
    {{f.input value=blankpage required=true}}
     {{f.submit label="Save"}}
{{/validated-form}}

Controller: 
import CustomersettingsValidations from '../validations/customersettings';

export default Controller.extend({
  
    CustomersettingsValidations,
    sortProperties: ['timestamp'],
    sortAscending: false, // sorts post by timestamp
    actions: {
      publishTheme: function() {
        var newTheme = this.store.createRecord('theme', {
          blankpage: this.get('blankpage'),
          timestamp: new Date().getTime()
        });
        newTheme.save();
      }
    }
});

**Comment by czosel** [comment]
Hi @onewiseburdman,
adding `required=true` to the input is not enough to trigger required validations. You'll have to add it to the validations file, in your case `validations/customersettings`. Also, it is usually prefered to use the `name` property of `f.input` to reference a property of your model instead of using `value` directly. I put together a [twiddle](https://ember-twiddle.com/3691a8576c35ff149bfc26a564ec5437?openFiles=templates.application.hbs%2C) that demostrates the basic usage. In case this doesn't solve your problem, please try changing the twiddle to showcase it!

**Comment by onewiseburdman** [comment]
That was it-thanks.  The twiddle helped tremendously.  I appreciate it.

**Comment by czosel** [comment]
Happy to hear that! You’re welcome ☺️
