### ISSUE TITLE
Add possibility to customize checkbox and radio style

### ISSUE THREAD

**Issue by makepanic** [adfinis-sygroup/ember-validated-form#82]
Hi,
Thanks for the great addon.

I was trying to customize the checkbox/radio input style but found it to be impossible.

Usually one hides the real input element and uses an adjacent sibling combinator to create a fake checkbox.
Something like `input[type=checkbox]:checked + div` is used to control the fake checkbox style.
Sadly it's not possible as this addon generates a label that wraps the input and its label text:

```
<label>
  <input type=checkbox/>
  {{label}}
</label>
```

The most backwards compatible way to solve this issue would be to wrap the label in an unstyled element:

```
<label>
  <input type=checkbox/>
  <span>{{label}}</span>
</label>
```

That way one could introduce a fake checkbox with `[type=checkbox] + span:before` and also style the label once the checkbox is checked.

Any thoughts on this? If the proposed solution is fine, I could open a PR.

**Comment by czosel** [comment]
Hi @makepanic,

that makes a lot of sense! I think wrapping the label inside `<span></span>` won't be noticed by most users of the addon - and we can still release it as a breaking change to remain strictly semver-compliant. I'd be happy to merge your PR!
