### ISSUE TITLE
Add possibility for tooltip next to input label

### ISSUE THREAD

**Issue by przywartya** [adfinis-sygroup/ember-validated-form#94]
Hello,
would you consider adding a tooltip for your input fields? I have added it in my project, but to do that, I had to copy your entire 'validated-input.hbs' (I could not use {{yield}}, because you are not exporting your templates :/). 

Twiddle with usage example: https://ember-twiddle.com/840f71a4f246d106872879c46d0477e4?openFiles=templates.application.hbs%2C

Thanks in advance :+1:

**Comment by czosel** [comment]
Hi @przywartya,
thanks for the issue and the twiddle! 
Currently, the `yield` in `validated-input` is used to support custom components (see [here](https://github.com/adfinis-sygroup/ember-validated-form#custom-input-elements)).

It would be nice to support a generic way of customizing the `label` of our inputs, and my colleague @anehx had the idea to allow passing a custom `label` component to the input, a bit like it's done in ember-power-select (see [here](http://ember-power-select.com/docs/the-search#ember665)). What do you think?

**Comment by przywartya** [comment]
Thanks for a rapid reply @czosel! 
That is actually a much better idea. 
Have a look here: https://ember-twiddle.com/840f71a4f246d106872879c46d0477e4?openFiles=templates.components.validated-input.hbs%2C 
I hope that I did not misunderstood your suggestion

**Comment by czosel** [comment]
Awesome, that's exactly what I meant!

In noticed two things in the twiddle:

* the checkbox contains a label inside a label, and `inputId` doesn't seem to work
* it might be nicer to define our own `label` component, and define it as a default instead of having to use `if` in the template (assuming that would work)

Otherwise, this looks great - would you like to open a PR? 😄

**Comment by przywartya** [comment]
Have a look:
- Usage: https://ember-twiddle.com/840f71a4f246d106872879c46d0477e4?openFiles=templates.components.validated-input.hbs%2C
- PR: https://github.com/adfinis-sygroup/ember-validated-form/pull/95

Thanks :blush:

**Comment by czosel** [comment]
Fixed by #95
