### ISSUE TITLE
Add autocomplete attribute binding

### ISSUE THREAD

**Issue by makepanic** [adfinis-sygroup/ember-validated-form#96]
Currently there is no easy way to set the `autocomplete` attribute on a validated-form input.
`autocomplete` makes it easier for users to fill forms as the browser can complete relevant values automatically.

- https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#autofill
- https://cloudfour.com/thinks/autofill-what-web-devs-should-know-but-dont/

If it's ok to add `autocomplete` support to validated-form, I can open a PR later.

**Comment by anehx** [comment]
Seems like a reasonable idea. However, it'd be nice if you could add it for `validated-input` and `validated-form`!
