### ISSUE TITLE
Bootstrap 4 support

### ISSUE THREAD

**Issue by mariusaiquest** [adfinis-sygroup/ember-validated-form#99]
Hi guys!

Very nice job with this addon!
Is there a way to use this with bootstrap 4?

Thanks,

**Comment by anehx** [comment]
Hi @mariusaiquest 

As far as I understand it bootstrap v4 did not change the class names or the html layout used by bootstrap v3, so it should just work the same! Did you try it and encounter problems?

**Comment by mariusaiquest** [comment]
Hi, thanks for your answer

Actually, it changed some class names and the way that the class names for the errors are used:
https://getbootstrap.com/docs/4.0/migration/#forms-1

Thanks,

**Comment by anehx** [comment]
Oh, I completely missed that part.. I'll try to add an example for usage with bootstrap v4. Thanks for your request!

**Comment by mariusaiquest** [comment]
Thanks alot!
